export const easingNames = [
  'linear',
  'inQuad',
  'outQuad',
  'inOutQuad',
  'inCubic',
  'outCubic',
  'inOutCubic',
  'inQuart',
  'outQuart',
  'inOutQuart',
  'inQuint',
  'outQuint',
  'inOutQuint',
  'inSine',
  'outSine',
  'inOutSine',
  'inExpo',
  'outExpo',
  'inOutExpo',
  'inCirc',
  'outCirc',
  'inOutCirc',
  'inElastic',
  'outElastic',
  'inOutElastic',
  'inBack',
  'outBack',
  'inOutBack',
  'inBounce',
  'outBounce',
  'inOutBounce',
] as const

export type EasingName = (typeof easingNames)[number]
